Python functionality
AlexandrVovk/common pull request #4
Opened 2019-10-22 22:57 UTC by yuriimchg

2019-10-28 13:29 UTC, dimigor requested changes

2019-10-28 13:29 UTC, dimigor commented on python_functionality/homework.py
> +    return data
try to simplify it

2019-10-28 13:29 UTC, dimigor commented on python_functionality/homework.py
> +            data_list.pop(redun_list)
what about dict comprehensions?

2019-11-01 20:04 UTC, AlexandrVovk commented on python_functionality/homework.py
> +    return data
done

2019-11-01 20:05 UTC, AlexandrVovk commented on python_functionality/homework.py
> +            data_list.pop(redun_list)
it was hard, but I did it

2019-11-02 17:49 UTC, dimigor approved these changes

2019-11-02 17:57 UTC, merged