add new homework flask intro
AlexandrVovk/common pull request #5
Opened 2019-10-28 16:55 UTC by AlexandrVovk

homework flask

2019-10-28 19:29 UTC, yuriimchg requested changes
привіт
гарне дз, але є декілька зауважень:

1) лінтер трохи свариться на форматування:
```main.py:10:1: E302 expected 2 blank lines, found 1
main.py:15:1: E302 expected 2 blank lines, found 1
main.py:22:1: W391 blank line at end of file```

2) зроби, будь ласка, текст на навігаційній панелі іншого кольору, ніж панель

2019-10-28 19:57 UTC, AlexandrVovk commented
> привіт
> гарне дз, але є декілька зауважень:
> 
> 1. лінтер трохи свариться на форматування:
> 
> ```
> main.py:15:1: E302 expected 2 blank lines, found 1
> main.py:22:1: W391 blank line at end of file```
> 
> 2) зроби, будь ласка, текст на навігаційній панелі іншого кольору, ніж панель
> ```

2019-10-28 20:46 UTC, yuriimchg submitted a review, later dismissed
_+_
вітаю з завершеним домашнім :tada: :fire: :rocket:

2019-11-05 19:27 UTC, yuriimchg approved these changes

2019-11-05 19:28 UTC, merged